name: main

on:
  push:
    branches: ['main']

jobs:
  call-reusable:
    uses: autopp/reusable-workflow-example/.github/workflows/send-slack.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  inplace:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: 'echo inplace job $JOB_NAME'
        env:
          JOB_NAME: '${{ github.job }}'
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,took,workflow,job,ref,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
