name: send-slack-yml

on:
  workflow_call:
    inputs:
      caller:
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-job:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # JOB_NAME: ${{ inputs.caller }} / send-slack-job
      JOB_NAME: "call-reusable / send-slack-job"
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: 'echo send-slack job "$JOB_NAME"'
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,took,workflow,job,ref,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: 'Hello'
        run: 'echo Hello'
